### ISSUE TITLE
Strange irregular rotation and shearing of boxes

### ISSUE THREAD

**Issue by kronpano** [after12am/eisenscript#45] opened 2016-10-19 20:45 UTC
I published my try-outs [here](https://playingwithstuff.000webhostapp.com/) (takes a bit to load and show the structure but it works - well - should work)
The structure is a regular one - the script is

> corner
> rule ARC maxdepth 66 {
>     { z 0.85 rx 4.5 s 0.95  } ARC
>     box
> }
> rule corner md 10{
>     { s 1 2 1.2 }ARC
>     {ry 36}corner 
> }

The problem is if you zoom in (mouse wheel) and look at the structure some arms are regular (1) but if you turn the structure (left click and drag/ right click shifts it) some are quite strange (2).
![arms](https://cloud.githubusercontent.com/assets/22873114/19536487/0cb75c7c-9644-11e6-9d25-08a384dc0b64.jpg)

Not sure why that should happen if the script is just turn and rotate.

**One - quite big difference to the original** Structure Synth is that boxes are not sheared they stay boxes.

The following script 
15 \* {rx 10 x 1.1 s 1 1.3 1}box
produces heavily sheared boxes in the original Structure Synth
![t2](https://cloud.githubusercontent.com/assets/22873114/19536711/fecc7a4c-9644-11e6-9c63-0d0ef9d25d9c.jpg)

but a tower of nice rectangular boxes in browser synth
![t1](https://cloud.githubusercontent.com/assets/22873114/19536722/0f91f0b4-9645-11e6-8b41-2b7f6af8617c.jpg)

This shearing also means that the structure I published on the website looks quite "rough" whereas in the original Structure Synth - due to the shearing - it is quite smooth
![image](https://cloud.githubusercontent.com/assets/22873114/19536867/bfaf7674-9645-11e6-960d-cae80203efae.png)

Just saying

**Comment by after12am** [comment] 2016-10-22 14:59
I have been doing my best for solution of this problem in past these three days. I wondered why this problem has been occurred. There is no bug causes this problem, however many times I checked my code. But I find the bug related to recursively rule calling instead. ( #48 ) This is fixed in v1.1.7.

I was bewildered, and then I checked transformation matrix which was getting after compiling the eisenscript code. I compared with the result which was got using [another library](https://evanw.github.io/lightgl.js/docs/matrix.html) that calculates transformation. The result is the same. 

Finally, I decided to create sample using another 3d library except three.js. I used [babylonjs](http://www.babylonjs.com/). The result is [here](http://after12am.github.io/eisenscript/test/babylonjs.html).

I have come a long way... I guess this problem has been caused by three.js. 

For resolving the problem, you have to use the another 3d renderer. But I do not know the suitable renderer. Sorry,

![default](https://cloud.githubusercontent.com/assets/678921/19620009/b7c8dae8-98ae-11e6-851e-159908726d6d.png)

**Comment by after12am** [comment] 2016-10-22 15:03
I guess this is the bug in structure synth. I guess that the bug is disclosed when using scaling and rotation in the same time.

![fecc7a4c-9644-11e6-9c63-0d0ef9d25d9c](https://cloud.githubusercontent.com/assets/678921/19620233/b9e99bc8-98b3-11e6-909c-092ec84a543a.jpg)

**Closed** 2020-04-10 10:22 UTC
